services:
  ml-prompt-optimizer:
    container_name: ml-prompt-optimizer
    image: refracta/ml-prompt-optimizer
    volumes:
      - /home/refracta:/home/refracta
      - /mnt/ext_sdb:/mnt/ext_sdb
    working_dir: /usr/src/
    privileged: true
    ipc: host
#    network_mode: host
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "22"