services:
  ml-c-v2:
    container_name: ml-c-v2
    image: refracta/ml-c-v2
    volumes:
      - /home/refracta:/home/refracta
      - /mnt/ext_sdb:/mnt/ext_sdb
    working_dir: /usr/src/
    privileged: true
    ipc: host
    network_mode: host
    restart: unless-stopped

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]