FROM nvcr.io/nvidia/pytorch:23.08-py3

RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install --yes \
    bash \
    build-essential \
    htop \
    locales \
    man \
    python3 \
    python3-pip \
    software-properties-common \
    sudo \
    systemd \
    systemd-sysv \
    tmux \
    unzip tar \
    vim nano \
    tzdata \
    wget curl \
    fzf \
    openssh-server \
    git \
    libgl1-mesa-glx